version: '3'

services:
  masterclass_project:
    image: mefistocl/masterclassproject:latest
    container_name: masterclass_project
    restart: "no"
    privileged: true
    environment:
      - DISPLAY=:0
      - GAZEBO_MODEL_PATH=/root/ros2_ws/src/the_construct_office_gazebo/models:/root/ros2_ws/src/ur_arm:$${GAZEBO_MODEL_PATH}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm  
      - /home/mefisto/masterclass/ros2_ws:/root/ros2_ws
      - /home/mefisto/masterclass/webapp:/root/webapp
    ports:
      - "11345:11345"
      - "11311:11311"
      - "80:80"
      - "9090:9090"
      - "7000:7000"
    #command: "bash -c 'source /root/ros2_ws/install/setup.bash && ros2 launch the_construct_office_gazebo starbots_ur3e.launch.xml'" 

# For ROS2 dont use network_mode: host. ROS2 uses Fast-DDS that would make some conflict when subscribing to the topics in other
# containers or from the host machine, thus use /dev/shm:/dev/shm  to share the memory

# To use a docker compose file  into a bash
# First docker-compose up then
# docker-compose run masterclass_project /bin/bash